export { default as Navbar } from './Navbar';
export { default as Header } from './Header';
export { default as CategoriesCard } from './CategoriesCard';
export { default as WhoAreWe } from './WhoAreWe';
export { default as Service } from './Service';
export { default as ContactUs } from './ContactUs';
export { default as WhyUs } from './WhyUs';
export { default as Footer } from './Footer';
export { default as CategoriesCardsContainer } from './CategoriesCardsContainer';
